# Generated by Django 5.1.7 on 2025-04-16 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchased_by', models.CharField(choices=[('user', 'User'), ('agent', 'Agent')], max_length=50)),
                ('purchased_type', models.CharField(choices=[('direct', 'Direct'), ('mlm_office', 'MLM Office')], max_length=50)),
                ('username', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('property_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('company_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('agent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_transactions', to='users.user')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
                ('purchased_agent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchased_agent_transactions', to='users.user')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transactions', to='users.user')),
            ],
        ),
    ]
