# Generated by Django 5.1.7 on 2025-04-03 12:36

import property.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('property_name', models.CharField(blank=True, max_length=150, null=True)),
                ('property_type', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=15, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=150, null=True)),
                ('owner_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('owner_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('agent_id', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('property_value', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('ownership_type', models.CharField(blank=True, max_length=100, null=True)),
                ('property_image', models.ImageField(blank=True, null=True, upload_to=property.models.property_image_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
