# Generated by Django 5.1.7 on 2025-04-16 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyimage',
            old_name='property_id',
            new_name='property',
        ),
        migrations.RenameField(
            model_name='propertyvideo',
            old_name='property_id',
            new_name='property',
        ),
    ]
