# Generated by Django 5.1.7 on 2025-04-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_availability_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='referral_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
